application: nonchang-game-server
version: 1
runtime: go
api_version: go1

handlers:

- url: /static
  static_dir: static
#   http_headers:
#     Access-Control-Allow-Origin: "*"
#     Access-Control-Allow-Headers: "*"
#     Access-Control-Allow-Methods: "GET, PUT, POST, OPTIONS, DELETE"

- url: /.*
  script: _go_app

- url: /_ah/spi/.*
  script: _go_app


- url: /favicon.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico
